#!/bin/bash
#

##########################################################
# Framadate manage ( create/delete)
# 
# dan.y.roche@gmail.com
#
# 1st version 20150612
#             20160123  fetch config from php
#             20160324  new mysql connection + fix env
#             20160512  framadate version 0.9.6
#             20161227  moved/modified to external application framadate
#
##########################################################

PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/opt/miscbin:/opt/java/bin:.
export PATH

##########################################################
# env stuff
# HOME does not seem to be set in apache env !
# we need it for mysql --login-path !
##########################################################

if [ "${HOME}" = "" ]
then
  WHOAMI=$(whoami)
  HOME=$(fgrep ${WHOAMI} /etc/passwd | awk -F ":" '{print $6}')
  export HOME
fi

##########################################################
# fetch Framadate config
##########################################################

# fetch global application config (php !)
#
MYSELF=$0
MYDIR=$(dirname ${MYSELF})
APPCONF=${MYDIR}/config.ini

if [ -s ${APPCONF} ]
then
    # fetch framadate base connection
    TMP3=$(cat ${APPCONF} | grep '^DB2SERV')
    DB2SERV=$(expr "${TMP3}" : '^DB2SERV *= *\(.*\)')
    TMP4=$(cat ${APPCONF} | grep '^DB2BASE')
    DB2BASE=$(expr "${TMP4}" : '^DB2BASE *= *\(.*\)')
    TMP5=$(cat ${APPCONF} | grep '^DB2USER')
    DB2USER=$(expr "${TMP5}" : '^DB2USER *= *\(.*\)')
    TMP6=$(cat ${APPCONF} | grep '^DB2PASS')
    DB2PASS=$(expr "${TMP6}" : '^DB2PASS *= *\(.*\)')
else
    echo "Can't find application config file - aborting !"
    exit 3
fi

type mysql_config_editor > /dev/null 2>&1
if [ $? -eq 0 ]
then
 # new mysql (5.6.6) connection
 # use mysql_config_editor on the server to initialize the login-path
 # use dbuser as login-path entry
 MYCMD="mysql --login-path=${DB2USER} -D${DB2BASE}"
else
 # old school mysql connection
 MYCMD="mysql -h${DB2SERV} -u${DB2USER} -p${DB2PASS} -D${DB2BASE}"
fi

##########################################################
# functions
##########################################################

usage () {
  echo "manage_framadate -c -t title | -d -i uuid "
  echo "where:"
  echo "  -c : create framadate"
  echo "   -t : framadate title "
  echo "  -d : delete framadate"
  echo "   -i uuid: framadate UUID"
  exit 1
}


##########################################################
# PARSE ARGS
##########################################################

ACTION="none"
VERBOZ=0
TITLE=""
UUID=""

while [ $OPTIND -le $# ] 
do
    getopts "cdt:j:i:v" OPT
    case $OPT in 
    "c" )
       ACTION="create"
       ;;
    "d" )
       ACTION="delete"
       ;;
    "i" )
       UUID=${OPTARG}
       ;;
    "t" )
       TITLE=${OPTARG}
       ;;
    "v" )
       VERBOZ=1
       ;;
    "?" ) 
       usage
       ;;
    esac
done

if [ "${ACTION}" = "none" ]
then 
  usage
fi

if  [ "${ACTION}" = "delete" ]
then 
 if [ "${UUID}" = "" ]
 then
  usage
 fi
fi

if  [ "${ACTION}" = "create" ]
then 
 if [ "${TITLE}" = "" ]
 then
  usage
 fi
fi

##########################################################
# DO IT
##########################################################

case ${ACTION} in

############ create #############
#
"create" )

  #------------------------
  # INIT

  NOW=$(date "+%s")
  # 20 years in the future, we dont care about the partner framadate !
  # it will be destroyed with the cloudsx
  END0=$((NOW + 630720000))
  END1=$(date "+%Y-%m-%d %H:%M:%S" -d @${END0})

  # dev/urandom bloque ????
  #UUIDADM=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 24 | head -n 1)
  UUIDADM=$(date +"${TITLE} %s" | md5sum | fold -w 24 | head -n 1)
  UUIDSND=${UUIDADM:0:16}

  DAT0=$((NOW + 604800))
  DAT1=$((NOW + 777600))

  #----------------------
  # LOAD 

  echo "insert into fd_poll set id='${UUIDSND}', admin_name='cloudsx', description='', title='${TITLE}', admin_id='${UUIDADM}', end_date='${END1}', format='D', editable=1;" | ${MYCMD}

  echo "insert into fd_slot set poll_id='${UUIDSND}', title='${DAT0}', moments='14h00';" | ${MYCMD}
  echo "insert into fd_slot set poll_id='${UUIDSND}', title='${DAT1}', moments='15h00';" | ${MYCMD}

  #----------------------
  # dislay the created framadate ID
  echo ${UUIDADM}  
  ;;

############ delete #############
#
"delete" )

  #-------------------------
  # DOIT 

  # on ne prend que UID simple
  UUIDSND=${UUID:0:16}
  
  echo "delete from fd_poll where id='${UUIDSND}';" | ${MYCMD}
  echo "delete from fd_slot where poll_id='${UUIDSND}';" | ${MYCMD}
  echo "delete from fd_vote where poll_id='${UUIDSND}';" | ${MYCMD}
  echo "delete from fd_comment where poll_id='${UUIDSND}';" | ${MYCMD}
  ;;

############ esac #############

esac

