#!/bin/bash
#

############################################
# create thumbnail for cloudsx
# 
# dan.y.roche@gmail.com  
#
# 1st version 20150405
#             20150419  add vid/aud icons
#             20160102  txt 1 page !
#             20160103  html thumb
#             20160123  fetch config from php
############################################

#############################################
# inotify seems not to initialize ENV fine
# so be sure ENV is here

SHELL=/bin/bash
LANG=fr_FR.UTF-8
HOME=/home/login/apache
PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/opt/miscbin:/opt/java/bin:.
export PATH SHELL LANG HOME

# do we need those ? hope not
#USER=apache
#LOGNAME=apache
#export USER LOGNAME

##########################################################
# fetch config
##########################################################

# fetch global application config (php !)
#
MYSELF=$0
MYDIR=$(dirname ${MYSELF})
APPCONF=${MYDIR}/../app/Config.php

if [ -s ${APPCONF} ]
then
  # get the config from php conf
  TMP1=$(cat ${APPCONF} | grep '^ *$this->TopAppDir')
  CDIR1=$(expr "${TMP1}" : ' *$this->TopAppDir *= *\"\(.*\)\"')
else
  echo "Can't find application config file - aborting !"
  exit 3
fi

CSXDIR=${CDIR1}

# verify 
if [ ! -d ${CSXDIR} ]
then
  echo "application dir ${CSXDIR} not found - aborting !"
  exit 4
fi

TSIZE=x60
TSUF=png
ICODIR=${CSXDIR}/default_icons
ICO_GEN=${ICODIR}/file.png
ICO_VID=${ICODIR}/video.png
ICO_AUD=${ICODIR}/audio.png
MAXSIZ=33554432

############################################
# args
THEDIR=$1

if [ ! -d ${THEDIR} ]
then
  exit 2
fi

 
if  [ ! -d ${THEDIR}/.thumbs ]
then
  mkdir ${THEDIR}/.thumbs
fi

######################
# function

GenerateThumb() {
 
 FIL=$1
 SIZ=$(stat -c "%s" ${THEDIR}/${FIL})   
 
 # get extension
 EXT0=$( expr "${FIL}" : '.*\.\([^\.]*\)')
 EXT=$(echo -n ${EXT0} | tr "[A-Z]" "[a-z]") 

 case ${EXT} in 
 gif | jpg | jpeg | png | bmp )
  convert -resize ${TSIZE} "${THEDIR}/${FIL}" "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  ;;

 pdf )
  pdftk "${THEDIR}/${FIL}" cat 1-1 output /tmp/thnz_$$.pdf
  convert -resize ${TSIZE} /tmp/thnz_$$.pdf "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  rm -f /tmp/thnz_$$.pdf
  ;;

 txt )
  head -n 58 "${THEDIR}/${FIL}" > /tmp/thnz_$$.txt
  convert -resize ${TSIZE}  /tmp/thnz_$$.txt "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  rm -f /tmp/thnz_$$.txt
  ;;

 html )
  convert -resize ${TSIZE} "${THEDIR}/${FIL}" /tmp/thnz_h2i_$$.${TSUF}
  if [ -s /tmp/thnz_h2i_$$.${TSUF} ]
  then
    mv /tmp/thnz_h2i_$$.${TSUF} "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  elif [ -s /tmp/thnz_h2i_$$-0.${TSUF} ]
  then
    mv /tmp/thnz_h2i_$$-0.${TSUF} "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  fi
  rm -f /tmp/thnz_h2i_$$*
  ;;

 doc | xls | ppt | docx | xlsx | pptx | odt | odg | odp | ods )
  if [ ${SIZ} -gt ${MAXSIZ} ]
  then
      cp ${ICO_GEN} "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  else
      /usr/bin/unoconv --stdout -f pdf "${THEDIR}/${FIL}" | pdftk - cat 1-1 output /tmp/thnz_$$.pdf
      convert -resize ${TSIZE} /tmp/thnz_$$.pdf "${THEDIR}/.thumbs/${FIL}.${TSUF}"
      rm -f /tmp/thnz_$$.pdf
  fi
  ;;

 mts | avi | mkv | mp4 | mpg | flv | wmv | mov )
  cp ${ICO_VID} "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  ;;

 mp3 | ogg | wav | mp4 | wma | flac | mid | midi )
  cp ${ICO_AUD} "${THEDIR}/.thumbs/${FIL}.${TSUF}"
  ;;

 * )
 cp ${ICO_GEN} "${THEDIR}/.thumbs/${FIL}.${TSUF}"

 esac

}
 

######################
# loop on file 

for ITEM in ${THEDIR}/*
do

 if [ ! -s "${ITEM}" ]
 then 
  continue
 fi

 BNI=$(basename "${ITEM}")

 if [ "${BNI}" = "index.html" ]
 then
  continue
 fi

 if [ ! -s "${THEDIR}/.thumbs/${BNI}.${TSUF}" ]
 then
  GenerateThumb "${BNI}"
  continue
 fi

 M1=$(stat --printf "%Y"  "${ITEM}")
 M2=$(stat --printf "%Y"  "${THEDIR}/.thumbs/${BNI}.${TSUF}")

 if [ ${M1} -gt ${M2} ]
 then
  GenerateThumb "${BNI}"
  continue
 fi

done

 
